services:
  web:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://neondb_owner:npg_REyJ3jAcxG1K@ep-bitter-violet-a9wlnktt-pooler.gwc.azure.neon.tech/neondb?sslmode=require"
      NEXT_PUBLIC_SERVER_URL: https://hss-k04a.onrender.com
    volumes:
      - .:/app
    command: ["npm", "start"]
